# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RMTJYTpz92Kco8nkCzXhLUZg5A9EkjuS

## Practical 1
"""

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

import re
import string

text = " NLP IS FUN!!! Python is POWERFUL. "

# 1. Lowercase
normalized = text.lower()

# 2. Replace runs of punctuation with a space
normalized = re.sub(r"[{}]+".format(re.escape(string.punctuation)), " ", normalized)

# 3. Collapse repeated whitespace and trim the ends
normalized = re.sub(r"\s+", " ", normalized).strip()

print("Original:  ", repr(text))
print("Normalized:", normalized)



"""## Practical 2

### Task 1
"""

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text = "This is a simple example of text processing with Python and NLTK."

tokens = word_tokenize(text)
stop_words = set(stopwords.words('english'))

filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

print("Tokens:", tokens)
print("Stop words removed:", filtered_tokens)
print("Final text:", " ".join(filtered_tokens))

"""### Task 2"""

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text = "The movie is not good and the ending is never boring."
stop_words = set(stopwords.words('english'))
keep_words = {"no", "not", "nor", "never"}

filtered = [
    word for word in word_tokenize(text)
    if word.lower() not in stop_words or word.lower() in keep_words
]
print(filtered)

"""## Practical 3

### Task 1
"""

import nltk
from nltk.tokenize import word_tokenize

sentence = "The quick brown fox jumps over the lazy dog."
tokens = word_tokenize(sentence)
tagged_words = nltk.pos_tag(tokens)
print(tagged_words)

"""### Task 2"""

sentence = "Students learn Python quickly."
tagged = nltk.pos_tag(word_tokenize(sentence))

for word, tag in tagged:
    print(f"{word:12} {tag}")

"""## Exercises A"""

import re

def normalize_text(text):
    return re.sub(r"\s+", " ", text.lower()).strip()

import re
import string

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"[{}]+".format(re.escape(string.punctuation)), " ", text)
    return re.sub(r"\s+", " ", text).strip()

print(normalize_text(' HELLO NLP Students!!! '))

def normalize_text(text, keep_digits=True):
    text = text.lower()
    text = re.sub(r"[{}]+".format(re.escape(string.punctuation)), " ", text)
    if not keep_digits:
        text = re.sub(r"\d+", " ", text)
    return re.sub(r"\s+", " ", text).strip()

print(normalize_text("Room 101 costs $50!"))
print(normalize_text("Room 101 costs $50!", keep_digits=False))

print(normalize_text("Well-known: it's 5 o'clock, isn't it?"))

"""## Exercise B"""

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

sentence = "The students are learning natural language processing."
stop_words = set(stopwords.words('english'))

tokens = word_tokenize(sentence)
filtered = [w for w in tokens if w.lower() not in stop_words]

print("Before:", tokens)
print("After: ", filtered)

keep_words = {"not", "never"}
sentence = "The movie is not good and the ending is never boring."

tokens = word_tokenize(sentence)
filtered = [w for w in tokens
            if w.lower() not in stop_words or w.lower() in keep_words]

print("Before:", tokens)
print("After: ", filtered)

print("Tokens before:", len(tokens))   # 12
print("Tokens after: ", len(filtered))  # 7

"""## Exercise C"""

sentence = "A small bird was singing beautifully."
tagged = nltk.pos_tag(word_tokenize(sentence))

for word, tag in tagged:
    print(f"{word:12} {tag}")
print(nltk.pos_tag(word_tokenize("They book a room")))
print(nltk.pos_tag(word_tokenize("They read a book")))

"""## Exercise D"""

import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"[{}]+".format(re.escape(string.punctuation)), " ", text)
    return re.sub(r"\s+", " ", text).strip()

stop_words = set(stopwords.words("english"))
keep_words = {"no", "not", "nor", "never"}

sentence = input("Enter a sentence: ")

normalized = normalize_text(sentence)
tokens = word_tokenize(normalized)
filtered = [w for w in tokens if w not in stop_words or w in keep_words]
pos_tags = nltk.pos_tag(word_tokenize(sentence))   # original sentence

print("\n1. Original:          ", sentence)
print("2. Normalized:        ", normalized)
print("3. Tokens:            ", tokens)
print("4. Stop words removed:", filtered)
print("5. POS tags (original):", pos_tags)

"""## Mini Project"""

import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def normalize_text(text):
    text = text.lower()
    pattern = r"[{}]+".format(re.escape(string.punctuation))
    text = re.sub(pattern, " ", text)
    return re.sub(r"\s+", " ", text).strip()

text = "NLP is interesting, and Python makes text processing easier!"
normalized = normalize_text(text)
tokens = word_tokenize(normalized)

stop_words = set(stopwords.words("english"))
filtered = [w for w in tokens if w not in stop_words]
pos_tags = nltk.pos_tag(tokens)

print("Original:", text)
print("Normalized:", normalized)
print("Tokens:", tokens)
print("Without stop words:", filtered)
print("POS tags:", pos_tags)
